# Generated by Django 5.0.6 on 2026-07-03 11:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Actual cash amount received in UGX.', max_digits=15)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('overpayment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money (MTN/Airtel)'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('reference_number', models.CharField(blank=True, help_text='Mobile money or bank transaction reference number.', max_length=100)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date the payment was physically received.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Allocation'), ('ALLOCATED', 'Allocated'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING', max_length=10)),
                ('reversal_reason', models.TextField(blank=True, help_text='Reason for reversal — required when status = REVERSED.')),
                ('reversal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='loans.loan')),
                ('recorded_by', models.ForeignKey(help_text='Cashier who received and recorded this payment.', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(editable=False, max_length=25, unique=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('overpayment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['loan', 'payment_date'], name='payments_pa_loan_id_e5e6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recorded_by', 'payment_date'], name='payments_pa_recorde_21a475_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
