# Generated by Django 5.0.6 on 2026-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('plan', models.CharField(choices=[('STARTER', 'Starter — up to 500 clients'), ('PROFESSIONAL', 'Professional — up to 2,000 clients'), ('ENTERPRISE', 'Enterprise — unlimited')], default='STARTER', max_length=20)),
                ('message', models.TextField(blank=True, help_text="Anything else you'd like us to know")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONTACTED', 'Contacted'), ('ONBOARDED', 'Onboarded'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'verbose_name': 'Company Registration',
                'verbose_name_plural': 'Company Registrations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
