# Generated by Django 5.0.6 on 2026-08-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_company_provisioning_status'),
        ('tenants', '0005_registration_failed_state_and_attempts'),
    ]

    operations = [
    ]
