# Generated by Django 5.0.6 on 2026-08-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_merge_20260808_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingattempt',
            name='registration',
        ),
        migrations.DeleteModel(
            name='PlatformAdmin',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='onboarded_at',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='schema_name',
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('CONTACTED', 'Contacted'), ('ONBOARDED', 'Onboarded'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='OnboardingAttempt',
        ),
    ]
