"""
reports/models.py
=================
Stores metadata about generated reports so they can be re-downloaded
without regenerating, and so the CEO has an audit trail of what was
exported and by whom.

Models
------
ReportSnapshot  – metadata for a generated report file (PDF or Excel)

Design notes
------------
* The actual report files (PDF / Excel) are generated on demand by
  reports/generators.py and stored under MEDIA_ROOT/reports/.

* We keep the model lean.  Heavy business logic lives in the generators,
  not here.

* The parameters field (JSONField) stores the filters used to produce
  the report (date range, loan product filter, etc.) so the exact same
  report can be regenerated or audited later.
"""

import uuid

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


def report_upload_path(instance, filename):
    """Upload path: reports/{report_type}/{filename}"""
    return f"reports/{instance.report_type}/{filename}"


class ReportSnapshot(models.Model):
    """
    A record of a report that was generated and exported.

    Created whenever a user exports a report to PDF or Excel.
    The file field stores the generated file so it can be re-downloaded
    for up to 30 days (clean up old files with a management command).
    """

    class ReportType(models.TextChoices):
        LOAN_BOOK         = "LOAN_BOOK",     _("Loan Book")
        COLLECTIONS       = "COLLECTIONS",   _("Collections Report")
        OVERDUE           = "OVERDUE",       _("Overdue Report")
        INCOME_STATEMENT  = "INCOME_STMT",   _("Monthly Income Statement")
        CASHIER_PERF      = "CASHIER_PERF",  _("Cashier Performance")
        CLIENT_STATEMENT  = "CLIENT_STMT",   _("Client Account Statement")

    class FileFormat(models.TextChoices):
        PDF   = "PDF",   _("PDF")
        EXCEL = "EXCEL", _("Excel (.xlsx)")

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    report_type = models.CharField(
        max_length=15,
        choices=ReportType.choices,
        db_index=True,
    )

    file_format = models.CharField(
        max_length=5,
        choices=FileFormat.choices,
    )

    # The generated file — stored in MEDIA_ROOT/reports/{report_type}/
    file = models.FileField(
        upload_to=report_upload_path,
        null=True, blank=True,
        help_text=_("Generated report file."),
    )

    # JSON snapshot of the filters applied when generating this report.
    # Example: {"date_from": "2024-01-01", "date_to": "2024-01-31", "product_id": null}
    parameters = models.JSONField(
        default=dict,
        help_text=_("Filter parameters used to generate this report."),
    )

    # Human-readable description auto-generated by the view
    title       = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)

    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="generated_reports",
    )

    generated_at = models.DateTimeField(auto_now_add=True)

    # Mark for deletion after this date (background cleanup task)
    expires_at   = models.DateTimeField(
        null=True, blank=True,
        help_text=_("File will be deleted after this date by the cleanup task."),
    )

    def __str__(self):
        return f"{self.get_report_type_display()} ({self.file_format}) — {self.generated_at:%Y-%m-%d %H:%M}"

    class Meta:
        verbose_name = _("Report Snapshot")
        verbose_name_plural = _("Report Snapshots")
        ordering = ["-generated_at"]
        indexes = [
            models.Index(fields=["report_type", "generated_at"]),
            models.Index(fields=["generated_by"]),
        ]
