# Generated by Django 5.0.6 on 2026-07-03 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('suppressed_until', models.DateField(blank=True, help_text='If set, reminders are suppressed until this date.', null=True)),
                ('suppression_reason', models.TextField(blank=True, help_text='Reason reminders were paused — required when suppressing.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_setting', to='loans.loan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder Setting',
                'verbose_name_plural': 'Reminder Settings',
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('trigger_type', models.CharField(choices=[('DUE_3D', 'Due in 3 Days'), ('DUE_1D', 'Due Tomorrow'), ('DUE_TODAY', 'Due Today'), ('OVD_1D', 'Overdue 1 Day'), ('OVD_7D', 'Overdue 7+ Days'), ('MANUAL', 'Manually Triggered')], max_length=10)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent Successfully'), ('FAILED', 'Failed'), ('PENDING', 'Pending / Queued')], db_index=True, default='PENDING', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder_logs', to='clients.client')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder_logs', to='loans.loan')),
                ('schedule_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_logs', to='loans.loanschedule')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['loan', 'channel', 'status'], name='reminders_r_loan_id_afc386_idx'), models.Index(fields=['created_at'], name='reminders_r_created_0e7f4e_idx'), models.Index(fields=['status'], name='reminders_r_status_dbb807_idx')],
            },
        ),
    ]
