# Generated by Django 5.0.6 on 2026-07-03 11:26

import clients.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique identifier.', primary_key=True, serialize=False)),
                ('client_number', models.CharField(editable=False, help_text='Auto-generated client reference number.', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=10)),
                ('nin', models.CharField(db_index=True, help_text='14-character Uganda NIN, e.g. CF20100122XXXXX', max_length=20, unique=True, verbose_name='National ID Number (NIN)')),
                ('phone_primary', models.CharField(help_text='Primary phone, Uganda format: +256XXXXXXXXX', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(help_text='Full physical address including LC1 area and district.')),
                ('district', models.CharField(default='Kampala', max_length=100)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-Employed'), ('BUSINESS', 'Business Owner'), ('UNEMPLOYED', 'Unemployed'), ('OTHER', 'Other')], default='EMPLOYED', max_length=15)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('employer_address', models.TextField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, help_text='Gross monthly income in UGX.', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive clients cannot apply for new loans.')),
                ('is_blacklisted', models.BooleanField(default=False, help_text='Blacklisted clients are blocked from all loan applications.')),
                ('blacklist_reason', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, help_text='Recent passport-size photograph of the client.', null=True, upload_to=clients.models.client_photo_path)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NIN', 'National ID Card'), ('PASSPORT', 'Passport'), ('DRIVING', 'Driving Licence'), ('PAYSLIP', 'Payslip'), ('UTILITY', 'Utility Bill'), ('OTHER', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to=clients.models.client_document_path)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(help_text='E.g. Spouse, Parent, Sibling, Friend', max_length=50)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('physical_address', models.TextField()),
                ('is_guarantor', models.BooleanField(default=False, help_text='Check if this person is also acting as loan guarantor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='clients.client')),
            ],
            options={
                'verbose_name': 'Next of Kin',
                'verbose_name_plural': 'Next of Kin',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nin'], name='clients_cli_nin_698c15_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_primary'], name='clients_cli_phone_p_57475a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name', 'first_name'], name='clients_cli_last_na_198e2f_idx'),
        ),
    ]
