# Generated by Django 5.0.6 on 2026-07-07 07:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('loans', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Credit balance created from overpayments and retained for future use.', max_digits=15),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('OVERPAYMENT', 'Overpayment Received'), ('APPLIED', 'Applied to Loan'), ('REFUNDED', 'Refunded to Client'), ('WRITTEN_OFF', 'Written Off to Income'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit added, Negative = credit used/removed', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='loans.loan')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='clients_cre_client__67551f_idx')],
            },
        ),
    ]
