# Generated by Django 5.0.6 on 2026-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('last', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='companysettings',
            name='processing_fee_method',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('RANGE', 'Range')], default='PERCENTAGE', help_text='Choose whether processing fees are calculated using a percentage or amount ranges.', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='processing_fee_ranges',
            field=models.TextField(blank=True, default='', help_text="Processing fee ranges as 'MIN-MAX:AMOUNT' per line, for example '0-500000:5000'."),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(help_text='ID of the entity affected', max_length=100),
        ),
    ]
