# Generated by Django 5.0.6 on 2026-07-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_receiptsequence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeChargeTier',
        ),
    ]
