# Generated by Django 5.0.6 on 2026-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_office_charge_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(default='Abacash', max_length=200),
        ),
    ]
