# Generated by Django 5.0.6 on 2026-08-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_companysettings_company_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional username for login (can be email, phone, or custom)', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
