# Generated by Django 5.0.6 on 2026-08-27 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalinjection',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_injections', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='capitalinjection',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money')], default='CASH', max_length=20),
        ),
    ]
