# Generated by Django 5.0.6 on 2026-07-03 11:26

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('LOAN_BOOK', 'Loan Book'), ('COLLECTIONS', 'Collections Report'), ('OVERDUE', 'Overdue Report'), ('INCOME_STMT', 'Monthly Income Statement'), ('CASHIER_PERF', 'Cashier Performance'), ('CLIENT_STMT', 'Client Account Statement')], db_index=True, max_length=15)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel (.xlsx)')], max_length=5)),
                ('file', models.FileField(blank=True, help_text='Generated report file.', null=True, upload_to=reports.models.report_upload_path)),
                ('parameters', models.JSONField(default=dict, help_text='Filter parameters used to generate this report.')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='File will be deleted after this date by the cleanup task.', null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Snapshot',
                'verbose_name_plural': 'Report Snapshots',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'generated_at'], name='reports_rep_report__370c55_idx'), models.Index(fields=['generated_by'], name='reports_rep_generat_bec448_idx')],
            },
        ),
    ]
