# Generated by Django 5.0.6 on 2026-07-03 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanschedule',
            name='paid_by_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries_paid', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='loanscheduleextension',
            name='extended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanscheduleextension',
            name='schedule_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='loans.loanschedule'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['nin'], name='loans_guara_nin_ac0906_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['phone_primary'], name='loans_guara_phone_p_0b86e2_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['is_active'], name='loans_guara_is_acti_f2bcdb_idx'),
        ),
        migrations.AddIndex(
            model_name='loanfee',
            index=models.Index(fields=['loan', 'status'], name='loans_loanf_loan_id_c0abe8_idx'),
        ),
        migrations.AddIndex(
            model_name='loanfee',
            index=models.Index(fields=['due_date'], name='loans_loanf_due_dat_1e7cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='loanguarantee',
            index=models.Index(fields=['loan', 'is_active'], name='loans_loang_loan_id_88f04c_idx'),
        ),
        migrations.AddIndex(
            model_name='loanguarantee',
            index=models.Index(fields=['guarantor', 'is_active'], name='loans_loang_guarant_baedcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanguarantee',
            unique_together={('guarantor', 'loan')},
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client', 'status'], name='loans_loan_client__a27993_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['disbursement_date'], name='loans_loan_disburs_33922a_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['risk_rating'], name='loans_loan_risk_ra_ca3399_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['par_category'], name='loans_loan_par_cat_fcf2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['branch', 'status'], name='loans_loan_branch__294559_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanrenewal',
            unique_together={('original_loan', 'new_loan')},
        ),
        migrations.AddIndex(
            model_name='loanrestructure',
            index=models.Index(fields=['loan', 'effective_date'], name='loans_loanr_loan_id_bb8670_idx'),
        ),
        migrations.AddIndex(
            model_name='loanschedule',
            index=models.Index(fields=['due_date', 'status'], name='loans_loans_due_dat_2e7162_idx'),
        ),
        migrations.AddIndex(
            model_name='loanschedule',
            index=models.Index(fields=['loan', 'status'], name='loans_loans_loan_id_2fb823_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanschedule',
            unique_together={('loan', 'period_number')},
        ),
    ]
