# Generated by Django 5.0.6 on 2026-07-24 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDisbursementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_disbursement_date', models.DateField(blank=True, null=True)),
                ('new_disbursement_date', models.DateField(blank=True, null=True)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('regenerate', 'Regenerate Schedule'), ('reschedule', 'Reschedule'), ('renew', 'Renewal')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_changes', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_audits', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Disbursement Audit',
                'verbose_name_plural': 'Disbursement Audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
